// Code generated by cmd/codegen. DO NOT EDIT.

package truenas

import (
	"context"
	"encoding/json"

	"github.com/gringolito/terraform-provider-truenas/internal/client"
)

type GroupGetGroupObjResult struct {
	GrName string   `json:"gr_name"`
	GrGid  int64    `json:"gr_gid"`
	GrMem  []string `json:"gr_mem"`
	Sid    *string  `json:"sid,omitempty"`
	Source string   `json:"source"`
	Local  bool     `json:"local"`
}

type Group struct {
	Id                   int64           `json:"id"`
	Gid                  int64           `json:"gid"`
	Name                 string          `json:"name"`
	Builtin              bool            `json:"builtin"`
	SudoCommands         []string        `json:"sudo_commands,omitempty"`
	SudoCommandsNopasswd []string        `json:"sudo_commands_nopasswd,omitempty"`
	Smb                  bool            `json:"smb,omitempty"`
	UsernsIdmap          json.RawMessage `json:"userns_idmap,omitempty"`
	Group                string          `json:"group"`
	Local                bool            `json:"local"`
	Sid                  *string         `json:"sid"`
	Roles                []string        `json:"roles"`
	Users                []int64         `json:"users,omitempty"`
	Immutable            bool            `json:"immutable"`
}

type GroupCreateArgs struct {
	Gid                  *int64          `json:"gid,omitempty"`
	Name                 string          `json:"name"`
	SudoCommands         []string        `json:"sudo_commands,omitempty"`
	SudoCommandsNopasswd []string        `json:"sudo_commands_nopasswd,omitempty"`
	Smb                  bool            `json:"smb,omitempty"`
	UsernsIdmap          json.RawMessage `json:"userns_idmap,omitempty"`
	Users                []int64         `json:"users,omitempty"`
}

type GroupGetGroupObjArgs struct {
	Groupname *string `json:"groupname,omitempty"`
	Gid       *int64  `json:"gid,omitempty"`
	SidInfo   bool    `json:"sid_info,omitempty"`
}

type GroupUpdateArgs struct {
	Name                 string          `json:"name,omitempty"`
	SudoCommands         []string        `json:"sudo_commands"`
	SudoCommandsNopasswd []string        `json:"sudo_commands_nopasswd"`
	Smb                  *bool           `json:"smb"`
	UsernsIdmap          json.RawMessage `json:"userns_idmap,omitempty"`
	Users                []int64         `json:"users"`
}

func GroupCreate(ctx context.Context, c client.Caller, args GroupCreateArgs) (int64, error) {
	raw, err := c.Call(ctx, "group.create", []any{args})
	if err != nil {
		return 0, err
	}
	var result int64
	if err := json.Unmarshal(raw, &result); err != nil {
		return 0, err
	}
	return result, nil
}

func GroupDelete(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "group.delete", []any{id})
	return err
}

func GroupGetGroupObj(ctx context.Context, c client.Caller, args GroupGetGroupObjArgs) (*GroupGetGroupObjResult, error) {
	raw, err := c.Call(ctx, "group.get_group_obj", []any{args})
	if err != nil {
		return nil, err
	}
	var result GroupGetGroupObjResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func GroupGetInstance(ctx context.Context, c client.Caller, id int64) (*Group, error) {
	raw, err := c.Call(ctx, "group.get_instance", []any{id})
	if err != nil {
		return nil, err
	}
	var result Group
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func GroupGetNextGid(ctx context.Context, c client.Caller) (int64, error) {
	raw, err := c.Call(ctx, "group.get_next_gid", []any{})
	if err != nil {
		return 0, err
	}
	var result int64
	if err := json.Unmarshal(raw, &result); err != nil {
		return 0, err
	}
	return result, nil
}

func GroupHasPasswordEnabledUser(ctx context.Context, c client.Caller) error {
	_, err := c.Call(ctx, "group.has_password_enabled_user", []any{})
	return err
}

func GroupQuery(ctx context.Context, c client.Caller) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "group.query", []any{})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func GroupUpdate(ctx context.Context, c client.Caller, id int64, args GroupUpdateArgs) (int64, error) {
	raw, err := c.Call(ctx, "group.update", []any{id, args})
	if err != nil {
		return 0, err
	}
	var result int64
	if err := json.Unmarshal(raw, &result); err != nil {
		return 0, err
	}
	return result, nil
}
