// Code generated by cmd/codegen. DO NOT EDIT.

package truenas

import (
	"context"
	"encoding/json"

	"github.com/gringolito/terraform-provider-truenas/internal/client"
)

type User struct {
	Id       int64           `json:"id"`
	Uid      int64           `json:"uid"`
	Username json.RawMessage `json:"username"`
	FullName string          `json:"full_name"`
}

type UserCreateArgs struct {
	Uid         *int64          `json:"uid,omitempty"`
	Username    string          `json:"username"`
	FullName    string          `json:"full_name"`
	UsernsIdmap json.RawMessage `json:"userns_idmap,omitempty"`
}

type UserUpdateArgs struct {
	Username string `json:"username,omitempty"`
	FullName string `json:"full_name,omitempty"`
}

func UserCreate(ctx context.Context, c client.Caller, args UserCreateArgs) (*User, error) {
	raw, err := c.Call(ctx, "user.create", []any{args})
	if err != nil {
		return nil, err
	}
	var result User
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func UserDelete(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "user.delete", []any{id})
	return err
}

func UserGetInstance(ctx context.Context, c client.Caller, id int64) (*User, error) {
	raw, err := c.Call(ctx, "user.get_instance", []any{id})
	if err != nil {
		return nil, err
	}
	var result User
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func UserUpdate(ctx context.Context, c client.Caller, id int64, args UserUpdateArgs) (*User, error) {
	raw, err := c.Call(ctx, "user.update", []any{id, args})
	if err != nil {
		return nil, err
	}
	var result User
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
