// Code generated by cmd/codegen. DO NOT EDIT.

package truenas

import (
	"context"
	"encoding/json"

	"github.com/gringolito/terraform-provider-truenas/internal/client"
)

type PoolAttachmentsResult struct {
	Type        string   `json:"type"`
	Service     *string  `json:"service"`
	Attachments []string `json:"attachments"`
}

type Pool struct {
	Id              int64                       `json:"id"`
	Name            string                      `json:"name"`
	Guid            string                      `json:"guid"`
	Status          string                      `json:"status"`
	Path            string                      `json:"path"`
	Scan            *map[string]json.RawMessage `json:"scan"`
	Expand          *map[string]json.RawMessage `json:"expand"`
	IsUpgraded      bool                        `json:"is_upgraded,omitempty"`
	Healthy         bool                        `json:"healthy"`
	Warning         bool                        `json:"warning"`
	StatusCode      *string                     `json:"status_code"`
	StatusDetail    *string                     `json:"status_detail"`
	Size            *int64                      `json:"size"`
	Allocated       *int64                      `json:"allocated"`
	Free            *int64                      `json:"free"`
	Freeing         *int64                      `json:"freeing"`
	DedupTableSize  *int64                      `json:"dedup_table_size"`
	DedupTableQuota *string                     `json:"dedup_table_quota"`
	Fragmentation   *string                     `json:"fragmentation"`
	SizeStr         *string                     `json:"size_str"`
	AllocatedStr    *string                     `json:"allocated_str"`
	FreeStr         *string                     `json:"free_str"`
	FreeingStr      *string                     `json:"freeing_str"`
	Autotrim        map[string]json.RawMessage  `json:"autotrim"`
	Topology        *map[string]json.RawMessage `json:"topology"`
}

type PoolImportFindResult struct {
	Name     string `json:"name"`
	Guid     string `json:"guid"`
	Status   string `json:"status"`
	Hostname string `json:"hostname"`
}

type PoolProcessesResult struct {
	Pid     int64   `json:"pid"`
	Name    string  `json:"name"`
	Service *string `json:"service"`
	Cmdline *string `json:"cmdline"`
}

type PoolAttachArgs struct {
	TargetVdev            string `json:"target_vdev"`
	NewDisk               string `json:"new_disk"`
	AllowDuplicateSerials bool   `json:"allow_duplicate_serials,omitempty"`
}

type PoolCreateArgs struct {
	Name                  string                     `json:"name"`
	Encryption            bool                       `json:"encryption,omitempty"`
	DedupTableQuota       json.RawMessage            `json:"dedup_table_quota,omitempty"`
	DedupTableQuotaValue  *int64                     `json:"dedup_table_quota_value,omitempty"`
	Deduplication         json.RawMessage            `json:"deduplication,omitempty"`
	Checksum              json.RawMessage            `json:"checksum,omitempty"`
	EncryptionOptions     map[string]json.RawMessage `json:"encryption_options,omitempty"`
	Topology              map[string]json.RawMessage `json:"topology"`
	AllowDuplicateSerials bool                       `json:"allow_duplicate_serials,omitempty"`
}

type PoolDdtPruneArgs struct {
	PoolName   string `json:"pool_name"`
	Percentage *int64 `json:"percentage,omitempty"`
	Days       *int64 `json:"days,omitempty"`
}

type PoolDetachArgs struct {
	Label string `json:"label"`
	Wipe  bool   `json:"wipe,omitempty"`
}

type PoolImportPoolArgs struct {
	Guid string  `json:"guid"`
	Name *string `json:"name,omitempty"`
}

type PoolOfflineArgs struct {
	Label string `json:"label"`
}

type PoolOnlineArgs struct {
	Label string `json:"label"`
}

type PoolRemoveArgs struct {
	Label string `json:"label"`
}

type PoolReplaceArgs struct {
	Label               string `json:"label"`
	Disk                string `json:"disk"`
	Force               bool   `json:"force,omitempty"`
	PreserveSettings    bool   `json:"preserve_settings,omitempty"`
	PreserveDescription bool   `json:"preserve_description,omitempty"`
}

type PoolUpdateArgs struct {
	DedupTableQuota       json.RawMessage            `json:"dedup_table_quota,omitempty"`
	DedupTableQuotaValue  *int64                     `json:"dedup_table_quota_value,omitempty"`
	Topology              map[string]json.RawMessage `json:"topology,omitempty"`
	AllowDuplicateSerials *bool                      `json:"allow_duplicate_serials"`
	Autotrim              string                     `json:"autotrim,omitempty"`
}

func PoolAttach(ctx context.Context, c client.Caller, id int64, args PoolAttachArgs) error {
	_, err := c.Call(ctx, "pool.attach", []any{id, args})
	return err
}

func PoolAttachments(ctx context.Context, c client.Caller, id int64) ([]*PoolAttachmentsResult, error) {
	raw, err := c.Call(ctx, "pool.attachments", []any{id})
	if err != nil {
		return nil, err
	}
	var result []*PoolAttachmentsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolCreate(ctx context.Context, c client.Caller, args PoolCreateArgs) (*Pool, error) {
	raw, err := c.Call(ctx, "pool.create", []any{args})
	if err != nil {
		return nil, err
	}
	var result Pool
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func PoolDdtPrefetch(ctx context.Context, c client.Caller) error {
	_, err := c.Call(ctx, "pool.ddt_prefetch", []any{})
	return err
}

func PoolDdtPrune(ctx context.Context, c client.Caller, args PoolDdtPruneArgs) error {
	_, err := c.Call(ctx, "pool.ddt_prune", []any{args})
	return err
}

func PoolDetach(ctx context.Context, c client.Caller, id int64, args PoolDetachArgs) error {
	_, err := c.Call(ctx, "pool.detach", []any{id, args})
	return err
}

func PoolExpand(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "pool.expand", []any{id})
	return err
}

func PoolExport(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "pool.export", []any{id})
	return err
}

func PoolFilesystemChoices(ctx context.Context, c client.Caller) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "pool.filesystem_choices", []any{})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolGetDisks(ctx context.Context, c client.Caller) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "pool.get_disks", []any{})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolGetInstance(ctx context.Context, c client.Caller, id int64) (*Pool, error) {
	raw, err := c.Call(ctx, "pool.get_instance", []any{id})
	if err != nil {
		return nil, err
	}
	var result Pool
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func PoolImportFind(ctx context.Context, c client.Caller) ([]*PoolImportFindResult, error) {
	raw, err := c.Call(ctx, "pool.import_find", []any{})
	if err != nil {
		return nil, err
	}
	var result []*PoolImportFindResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolImportPool(ctx context.Context, c client.Caller, args PoolImportPoolArgs) error {
	_, err := c.Call(ctx, "pool.import_pool", []any{args})
	return err
}

func PoolIsUpgraded(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "pool.is_upgraded", []any{id})
	return err
}

func PoolOffline(ctx context.Context, c client.Caller, id int64, args PoolOfflineArgs) error {
	_, err := c.Call(ctx, "pool.offline", []any{id, args})
	return err
}

func PoolOnline(ctx context.Context, c client.Caller, id int64, args PoolOnlineArgs) error {
	_, err := c.Call(ctx, "pool.online", []any{id, args})
	return err
}

func PoolProcesses(ctx context.Context, c client.Caller, id int64) ([]*PoolProcessesResult, error) {
	raw, err := c.Call(ctx, "pool.processes", []any{id})
	if err != nil {
		return nil, err
	}
	var result []*PoolProcessesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolQuery(ctx context.Context, c client.Caller) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "pool.query", []any{})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func PoolRemove(ctx context.Context, c client.Caller, id int64, args PoolRemoveArgs) error {
	_, err := c.Call(ctx, "pool.remove", []any{id, args})
	return err
}

func PoolReplace(ctx context.Context, c client.Caller, id int64, args PoolReplaceArgs) error {
	_, err := c.Call(ctx, "pool.replace", []any{id, args})
	return err
}

func PoolScrub(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "pool.scrub", []any{id})
	return err
}

func PoolUpdate(ctx context.Context, c client.Caller, id int64, args PoolUpdateArgs) (*Pool, error) {
	raw, err := c.Call(ctx, "pool.update", []any{id, args})
	if err != nil {
		return nil, err
	}
	var result Pool
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func PoolUpgrade(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "pool.upgrade", []any{id})
	return err
}

func PoolValidateName(ctx context.Context, c client.Caller) error {
	_, err := c.Call(ctx, "pool.validate_name", []any{})
	return err
}
