// Code generated by cmd/codegen. DO NOT EDIT.

package truenas

import (
	"context"
	"encoding/json"

	"github.com/gringolito/terraform-provider-truenas/internal/client"
)

type SharingSmb struct {
	Id                          int64                      `json:"id"`
	Purpose                     string                     `json:"purpose,omitempty"`
	Name                        string                     `json:"name"`
	Path                        json.RawMessage            `json:"path"`
	Enabled                     bool                       `json:"enabled,omitempty"`
	Comment                     string                     `json:"comment,omitempty"`
	Readonly                    bool                       `json:"readonly,omitempty"`
	Browsable                   bool                       `json:"browsable,omitempty"`
	AccessBasedShareEnumeration bool                       `json:"access_based_share_enumeration,omitempty"`
	Locked                      *bool                      `json:"locked"`
	Audit                       map[string]json.RawMessage `json:"audit,omitempty"`
	Options                     *json.RawMessage           `json:"options,omitempty"`
}

type SharingSmbCreateArgs struct {
	Purpose                     string                     `json:"purpose,omitempty"`
	Name                        string                     `json:"name"`
	Path                        json.RawMessage            `json:"path"`
	Enabled                     bool                       `json:"enabled,omitempty"`
	Comment                     string                     `json:"comment,omitempty"`
	Readonly                    bool                       `json:"readonly,omitempty"`
	Browsable                   bool                       `json:"browsable,omitempty"`
	AccessBasedShareEnumeration bool                       `json:"access_based_share_enumeration,omitempty"`
	Audit                       map[string]json.RawMessage `json:"audit,omitempty"`
	Options                     *json.RawMessage           `json:"options,omitempty"`
}

type SharingSmbGetaclArgs struct {
	ShareName string `json:"share_name"`
}

type SharingSmbSetaclArgs struct {
	ShareName string                       `json:"share_name"`
	ShareAcl  []map[string]json.RawMessage `json:"share_acl,omitempty"`
}

type SharingSmbSharePrecheckArgs struct {
	Name *string `json:"name,omitempty"`
}

type SharingSmbUpdateArgs struct {
	Purpose                     string                     `json:"purpose,omitempty"`
	Name                        string                     `json:"name,omitempty"`
	Path                        json.RawMessage            `json:"path,omitempty"`
	Enabled                     bool                       `json:"enabled,omitempty"`
	Comment                     string                     `json:"comment,omitempty"`
	Readonly                    bool                       `json:"readonly,omitempty"`
	Browsable                   bool                       `json:"browsable,omitempty"`
	AccessBasedShareEnumeration bool                       `json:"access_based_share_enumeration,omitempty"`
	Audit                       map[string]json.RawMessage `json:"audit,omitempty"`
	Options                     *json.RawMessage           `json:"options,omitempty"`
}

func SharingSmbCreate(ctx context.Context, c client.Caller, args SharingSmbCreateArgs) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.create", []any{args})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingSmbDelete(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "sharing.smb.delete", []any{id})
	return err
}

func SharingSmbGetInstance(ctx context.Context, c client.Caller, id int64) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.get_instance", []any{id})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingSmbGetacl(ctx context.Context, c client.Caller, args SharingSmbGetaclArgs) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.getacl", []any{args})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingSmbPresets(ctx context.Context, c client.Caller) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.presets", []any{})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingSmbQuery(ctx context.Context, c client.Caller) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "sharing.smb.query", []any{})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func SharingSmbSetacl(ctx context.Context, c client.Caller, args SharingSmbSetaclArgs) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.setacl", []any{args})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingSmbSharePrecheck(ctx context.Context, c client.Caller, args SharingSmbSharePrecheckArgs) error {
	_, err := c.Call(ctx, "sharing.smb.share_precheck", []any{args})
	return err
}

func SharingSmbUpdate(ctx context.Context, c client.Caller, id int64, args SharingSmbUpdateArgs) (*SharingSmb, error) {
	raw, err := c.Call(ctx, "sharing.smb.update", []any{id, args})
	if err != nil {
		return nil, err
	}
	var result SharingSmb
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
