// Code generated by cmd/codegen. DO NOT EDIT.

package truenas

import (
	"context"
	"encoding/json"

	"github.com/gringolito/terraform-provider-truenas/internal/client"
)

type SharingNfs struct {
	Id              int64    `json:"id"`
	Path            string   `json:"path"`
	Aliases         []string `json:"aliases,omitempty"`
	Comment         string   `json:"comment,omitempty"`
	Networks        []string `json:"networks,omitempty"`
	Hosts           []string `json:"hosts,omitempty"`
	Ro              bool     `json:"ro,omitempty"`
	MaprootUser     *string  `json:"maproot_user,omitempty"`
	MaprootGroup    *string  `json:"maproot_group,omitempty"`
	MapallUser      *string  `json:"mapall_user,omitempty"`
	MapallGroup     *string  `json:"mapall_group,omitempty"`
	Security        []string `json:"security,omitempty"`
	Enabled         bool     `json:"enabled,omitempty"`
	Locked          *bool    `json:"locked"`
	ExposeSnapshots bool     `json:"expose_snapshots,omitempty"`
}

type SharingNfsCreateArgs struct {
	Path            string   `json:"path"`
	Aliases         []string `json:"aliases,omitempty"`
	Comment         string   `json:"comment,omitempty"`
	Networks        []string `json:"networks,omitempty"`
	Hosts           []string `json:"hosts,omitempty"`
	Ro              *bool    `json:"ro,omitempty"`
	MaprootUser     *string  `json:"maproot_user,omitempty"`
	MaprootGroup    *string  `json:"maproot_group,omitempty"`
	MapallUser      *string  `json:"mapall_user,omitempty"`
	MapallGroup     *string  `json:"mapall_group,omitempty"`
	Security        []string `json:"security,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
	ExposeSnapshots *bool    `json:"expose_snapshots,omitempty"`
}

type SharingNfsUpdateArgs struct {
	Path            string    `json:"path,omitempty"`
	Aliases         *[]string `json:"aliases,omitempty"`
	Comment         string    `json:"comment,omitempty"`
	Networks        *[]string `json:"networks,omitempty"`
	Hosts           *[]string `json:"hosts,omitempty"`
	Ro              *bool     `json:"ro,omitempty"`
	MaprootUser     *string   `json:"maproot_user,omitempty"`
	MaprootGroup    *string   `json:"maproot_group,omitempty"`
	MapallUser      *string   `json:"mapall_user,omitempty"`
	MapallGroup     *string   `json:"mapall_group,omitempty"`
	Security        *[]string `json:"security,omitempty"`
	Enabled         *bool     `json:"enabled,omitempty"`
	ExposeSnapshots *bool     `json:"expose_snapshots,omitempty"`
}

func SharingNfsCreate(ctx context.Context, c client.Caller, args SharingNfsCreateArgs) (*SharingNfs, error) {
	raw, err := c.Call(ctx, "sharing.nfs.create", []any{args})
	if err != nil {
		return nil, err
	}
	var result SharingNfs
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingNfsDelete(ctx context.Context, c client.Caller, id int64) error {
	_, err := c.Call(ctx, "sharing.nfs.delete", []any{id})
	return err
}

func SharingNfsGetInstance(ctx context.Context, c client.Caller, id int64) (*SharingNfs, error) {
	raw, err := c.Call(ctx, "sharing.nfs.get_instance", []any{id})
	if err != nil {
		return nil, err
	}
	var result SharingNfs
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func SharingNfsQuery(ctx context.Context, c client.Caller, filters ...QueryFilter) (json.RawMessage, error) {
	raw, err := c.Call(ctx, "sharing.nfs.query", []any{filtersToRaw(filters)})
	if err != nil {
		return nil, err
	}
	var result json.RawMessage
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return result, nil
}

func SharingNfsUpdate(ctx context.Context, c client.Caller, id int64, args SharingNfsUpdateArgs) (*SharingNfs, error) {
	raw, err := c.Call(ctx, "sharing.nfs.update", []any{id, args})
	if err != nil {
		return nil, err
	}
	var result SharingNfs
	if err := json.Unmarshal(raw, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
